version: 2

models:
  - name: stg_xkcd_comics
    description: Standardized staging layer for XKCD comics data
    columns:
      - name: comic_id
        description: Unique identifier for each comic
        tests:
          - unique
          - not_null
      - name: title
        description: Title of the comic
        tests:
          - not_null
      - name: alt_text
        description: Alternative text shown when hovering over the comic
      - name: img_url
        description: URL of the comic image
      - name: published_date
        description: Publication date of the comic
        tests:
          - not_null
      - name: transcript
        description: Text transcript of the comic
      - name: loaded_at
        description: Timestamp when the record was initially loaded
      - name: dbt_updated_at
        description: Timestamp when the record was last updated by dbt

  - name: dim_comics
    description: Dimension table containing comic attributes and metadata
    columns:
      - name: comic_id
        description: Primary key - Unique identifier for each comic
        tests:
          - unique
          - not_null
      - name: title
        description: Title of the comic
        tests:
          - not_null
      - name: title_length
        description: Number of characters in the title, used for cost calculation
        tests:
          - not_null
      - name: alt_text
        description: Alternative text shown when hovering over the comic
      - name: img_url
        description: URL of the comic image
      - name: published_date
        description: Publication date of the comic
        tests:
          - not_null
      - name: transcript
        description: Text transcript of the comic
      - name: loaded_at
        description: Timestamp when the record was initially loaded
      - name: dbt_updated_at
        description: Timestamp when the record was last updated by dbt

  - name: fct_comic_metrics
    description: Fact table containing business metrics for each comic
    columns:
      - name: comic_id
        description: Foreign key to dim_comics
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('dim_comics')
              field: comic_id
      - name: title_cost_euros
        description: Cost of the comic title (5 euros per letter)
        tests:
          - not_null
      - name: estimated_views
        description: Estimated number of views (random * 10000)
        tests:
          - not_null
      - name: customer_rating
        description: Customer rating between 1.0 and 10.0
        tests:
          - not_null
      - name: dbt_updated_at
        description: Timestamp when the record was last updated by dbt

  - name: fct_monthly_metrics
    description: Monthly aggregated fact table containing metrics for business reporting
    columns:
      - name: year_month
        description: Year and month of publication
        tests:
          - not_null
          - unique
      - name: comics_count
        description: Number of comics published in the month
        tests:
          - not_null
      - name: total_cost_euros
        description: Total cost of comics published in the month
        tests:
          - not_null
      - name: avg_views
        description: Average number of views per comic in the month
        tests:
          - not_null
      - name: avg_rating
        description: Average customer rating for comics in the month
        tests:
          - not_null